<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-15T22:10:28 IST" name="Test Suite" finished-at="2024-12-15T22:10:35 IST" duration-ms="7732">
    <groups>
    </groups>
    <test started-at="2024-12-15T22:10:28 IST" name="Test" finished-at="2024-12-15T22:10:35 IST" duration-ms="7732">
      <class name="pageTests.LandingPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:pageTests.LandingPageTest@6f15d60e]" started-at="2024-12-15T22:10:28 IST" name="setUp" finished-at="2024-12-15T22:10:31 IST" duration-ms="3779" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Verify_login_with_valid_credentials()[pri:0, instance:pageTests.LandingPageTest@6f15d60e]" started-at="2024-12-15T22:10:31 IST" name="Verify_login_with_valid_credentials" finished-at="2024-12-15T22:10:32 IST" duration-ms="527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_login_with_valid_credentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pageTests.LandingPageTest@6f15d60e]" started-at="2024-12-15T22:10:32 IST" name="tearDown" finished-at="2024-12-15T22:10:32 IST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:pageTests.LandingPageTest@6f15d60e]" started-at="2024-12-15T22:10:32 IST" name="setUp" finished-at="2024-12-15T22:10:34 IST" duration-ms="1817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verify_error_message_invalid_credentials()[pri:0, instance:pageTests.LandingPageTest@6f15d60e]" started-at="2024-12-15T22:10:34 IST" name="verify_error_message_invalid_credentials" finished-at="2024-12-15T22:10:35 IST" duration-ms="1038" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email orpassword.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email orpassword.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageTests.LandingPageTest.verify_error_message_invalid_credentials(LandingPageTest.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_error_message_invalid_credentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pageTests.LandingPageTest@6f15d60e]" started-at="2024-12-15T22:10:35 IST" name="tearDown" finished-at="2024-12-15T22:10:35 IST" duration-ms="138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pageTests.LandingPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Test Suite -->
</testng-results>
